cmake_minimum_required(VERSION 3.8)
project(p213_msgs)
find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(rclcpp REQUIRED)
rosidl_generate_interfaces(${PROJECT_NAME} "msg/Foo.msg")
rosidl_get_typesupport_target(cpp_ts ${PROJECT_NAME} "rosidl_typesupport_cpp")
add_executable(foo_pub src/foo_pub.cpp)
target_link_libraries(foo_pub rclcpp::rclcpp ${cpp_ts})
add_executable(foo_sub src/foo_sub.cpp)
target_link_libraries(foo_sub rclcpp::rclcpp ${cpp_ts})
install(TARGETS foo_pub foo_sub DESTINATION lib/${PROJECT_NAME})
ament_export_dependencies(rosidl_default_runtime)
ament_package()
